config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users
  # get "/users", to: "users#index"
  # get "/users/:id", to: "users#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @users = @q.result
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RansackDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :phone %><br>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/index.html.erb
<h1>Welcome</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %><br />
  <%= f.submit%>
<% end %>

<table border="2">
  <thead>
  <th>Name</th>
  <th>Phone Number</th>
  <th>Edit</th>
  <th>Show</th>
  <th>Destroy</th>
  </thead>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.phone %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %>
    <td><%= link_to 'Show', user_path(user) %>
    <td><%= link_to 'Destroy', user_path(user), method: :delete %>
  </tr>
  <% end %>
</table>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>User</h1>

<%= render partial: 'form', locals: { user: @user } %>    <!--locals will convert instance to local -->

app/views/users/show.html.erb
Name : <%= @user.name %> <br />
Phone : <%= @user.phone %> <br />

<%= link_to 'Back', users_path %>